spring:
  jackson:
    time-zone: Europe/Stockholm

profile:
  location: url:http://YOURPROFILESERVERURL/encore/prod/master/profiles.yml

encore-settings:
  local-temporary-encode: true
  audio-mix-presets:
    default:
      fallback-to-auto: false
      default-pan:
        2: stereo| c0 = c0 + 0.707*c2 + 0.707*c4 | c1 = c1 + 0.707*c2 + 0.707*c5

      pan-mapping:
        6:
          2: stereo|c0=1.0*c0+0.707*c2+0.707*c4|c1=1.0*c1+0.707*c2+0.707*c5
    de:
      fallback-to-auto: false
      pan-mapping:
        6:
          2: stereo|c0<0.25*c0+1.5*c2+0.25*c4|c1<0.25*c1+1.5*c2+0.25*c5

redis:
  subscription-connection-pool-size: 25
  connection-pool-size: 32
  connection-minimum-idle-size: 5
  uri: redis://YOURINSTANCE:6379
  db: 1
