
=== Homebrew AVTools

So you noticed that the FFmpeg Docker Example in the quickstart used the Repository Manager Brew? The creators of *Encore*, SVT, have released their Brew Formulas on https://github.com/svt/homebrew-avtools[GitHub: Homebrew-AVTools].

That means it will be easier for you to try out *Encore*.

For example, here is the *Encore* FFmpeg Brew Formula that with minor modifications, uses formulas for X264, X265, and SVT's subtitle filter.
These Brew formulas be configured as you wish.

NOTE: To use and install this version of FFmpeg locally, follow the examples given at the https://github.com/svt/homebrew-avtools/blob/main/README.md[Homebrew AVTools README].

.The SVT *Encore* FFmpeg Brew Formula
[source, ruby]
----
include::https://raw.githubusercontent.com/svt/homebrew-avtools/main/Formula/ffmpeg-encore.rb[]
----

CAUTION: If you use Homebrew-AVTools, the version of FFmpeg in use might be updated without notice.


=== Profiles

.Profile example, main
[source, yaml]
----
include::https://raw.githubusercontent.com/svt/encore-doc/main/src/docs/asciidoc/examples/profile/profiles.yml[]
----

.Profile example, x264 codec with forced keyframes
[source, yaml]
----
include::https://raw.githubusercontent.com/svt/encore-doc/main/src/docs/asciidoc/examples/profile/withforcekeyframe.yml[]
----

.Profile example, x264 codec
[source, yaml]
----
include::https://raw.githubusercontent.com/svt/encore-doc/main/src/docs/asciidoc/examples/profile/video.yml[]
----

=== The Future

We have a few ideas where we would like to go with Encore. We are focusing on the features we need, but we are always open to suggestion and discussion, if you would like to contribute to the project.