== Appendix

=== Application Properties

Beside the rich configuration possibilities of https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html[Spring Boot and friends], a few custom properties can be specified inside your application.properties file, inside your application.yml file, or as command line switches.

[[customapplicationproperties]]
.Custom Application Properties - *prefix: encore-settings*
[grid=none,frame=sides]
|===
| Key | Default | Description

| local-temporary-encode
| false
| if true, encoding is done in a temporary folder on the Encore instance currently running the job. When done, the results are moved to the where the Encore Job's output folder path is pointing.

| audio-mix-presets
| a default <<audiomixpreset>> is created
| a list of <<audiomixpreset>>s to use

| concurrency
| 2
| Max nr of currently running encoding tasks (property starts at 0, so 0 gives 1 task).

| poll-initial-delay
| 10
| initial wait time in seconds before task starts.

| poll-delay
| 5
| wait before polling, in seconds, for next task after compilation of the current task.

| redis-key-prefix
| encore
| the prefix to identify your redis queue. Redis keys are named "$redisKeyPrefix-queue-$queueNo"

| security.enabled
| false
| enables basic auth, TODO: describe basic security logic

| security.user-password
|
| password for regular user

| security.admin-password
|
| password for the admin user

| open-api.title
| SVT Encore OpenAPI
| title shown in the OpenAPI url summary header

| open-api.description
| "Endpoints for Encore"
| description shown in the OpenAPI url summary header

| open-api.contact-name
|
| contact name shown in the OpenAPI gui summary header

| open-api.contact-email
|
| contact email shown in the OpenAPI gui summary header

| open-api.contact-url
|
| contact url shown in the OpenAPI gui summary header
|===


[[audiomixpreset]]
.AudioMixPreset
[grid=none,frame=sides]
|===
| Field | Description | Constraint | Default

| fallback-to-auto
| if true, sets the output audio channels to the number given by the <<audioencode>> field channel.
| the following conditions needs to apply for it to take effect:

    set to true

    nr of audio channels in input file > 0

<<audioencode>> channels = 2 OR between 1 and the "nr of audio channels in input file"

| true

| default-pan
| if configured, maps "autofound input audio channels" to the configured output channel configuration
| input file channels: configured <<audioencode>> channel: the https://ffmpeg.org/ffmpeg-filters.html#pan[pan filter] configuration to use

 See the concrete <<profiles>> for yaml example.

 Any configuration found in pan-mapping would take precedence over this configuration

|

| pan-mapping
| if configured, maps "found input audio channels" to the configured matching output channel configurations
| input file channels: configured <<audioencode>> channel: https://ffmpeg.org/ffmpeg-filters.html#pan[the pan filter] configuration which should be used.

  See the concrete <<configurationexample>> for yaml-examples.

  Any configuration here takes precedence over configurations in default-pan

|
|===

_For, clarity, here is how an encore-setting configuration with audio-mix-presets could look like in real life._


[[configurationexample]]
.encore-settings configuration example
[source, yaml]
----
include::https://raw.githubusercontent.com/svt/encore-doc/main/src/docs/asciidoc/examples/configuration/application-prod.yml[]
----



[[running_encore]]
=== Running Encore

As a complement to the UserGuide, here is a few more examples on how you can try out **Encore**.

* Using Docker-Compose
* Using Spring Boot BootRun
* Building an Docker Image and run Encore in a Docker Container


==== Example: using Docker Compose

* This step requires:
** https://docs.docker.com/compose/install/Docker-compose[Docker Compose]


- Use a docker-compose.yml

[source,yaml]
....
include::examples/docker/docker-compose.yml[]
....

and then

Linux
[source,console]
....
$ ./docker-compose up
....

Mac
[source,console]
....
$ ./docker compose up
....

and you should see Encore starting up.

IMPORTANT: By default, there are two folders mapped to your host system by using the example docker-compose file. 
**/tmp/input and /tmp/output**, which we will refer to as the **inputdir** and the **outputdir**
_Change these (in the docker-compose file) to something that suits your environment if you are not running on Linux. 
For example /Users/<YOURUSER>/input:/tmp/input should be fine on macos._

===== Get the IP

On Linux:
- To find the IP Docker-Compose creates (so that you can access Encore's api).


[source,console]
....
$ docker inspect <nameOfDirectoryYouAreRunningFrom>_encorenet
....

NOTE: By design Docker-compose creates a network called <nameOfDirectoryYouAreRunningFrom>_encorenet

On macos:
Use 'localhost'

Got the IP? - great! Continue to <<posting-your-first-encorejob>>

==== Example: run Encore with Spring Boot bootRun

You can run *Encore* on your local machine by starting up a local developer Application Profile:

.In the *Encore* root folder:
[source,bash]
----
foobar@foo:~$ SPRING_PROFILES_ACTIVE=local ./gradlew clean bootRun
----

NOTE: This will use the _src/main/resources/application-local.yml_ configuration profile in *Encore*.

If the startup fails, verify that you are fulfilling the <<requirements-run-local-boot,requirements>>

Continue to <<posting-your-first-encorejob>>

==== Example: run Encore in a Docker Image

- Create or find a base FFmpeg/Mediainfo Docker image.

The given example installs a recent version of FFmpeg, with a few FFmpeg filters, and mediainfo.
Modify as needed, using a tap of https://docs.brew.sh/Homebrew-on-Linux[Homebrew] as an installation base.

.A FFmpeg Dockerfile example (click to expand)
[%collapsible]
====
[source,dockerfile]
----
include::examples/docker/FFmpegDockerfile[]
----

====

.With the environment variable DOCKER_BASE_IMAGE pointing to your FFmpeg Docker Image
[source,bash]
----
foobar@foo:~$ docker build -t encore-docker --build-arg DOCKER_BASE_IMAGE=<yourdockerbaseimage:youjustbuilt> . 

foobar@foo:~$ docker run --network=host -v /tmp/input:/tmp/input -v /tmp/output:/tmp/output -e SPRING_PROFILES_ACTIVE='local' encore-docker
----

Continue to <<posting-your-first-encorejob>>

=== Homebrew AVTools

So you noticed that the FFmpeg Docker Example in the quickstart used the Repository Manager Brew?
The creators of *Encore*, have released their Brew Formulas on https://github.com/svt/homebrew-avtools[GitHub: Homebrew AVTools].

For example, here is the *Encore* FFmpeg Brew Formula that with minor modifications, uses formulas for X264, X265, and SVT's subtitle filter.

NOTE: To use and install this version of FFmpeg locally, follow the examples given at the https://github.com/svt/homebrew-avtools/blob/main/README.md[Homebrew AVTools README].

.The SVT *Encore* FFmpeg Brew Formula
[source, ruby]
----
include::https://raw.githubusercontent.com/svt/homebrew-avtools/main/Formula/ffmpeg-encore.rb[]
----

CAUTION: If you use Homebrew-AVTools, the version of FFmpeg in use might be updated without *any* notice.

=== Profiles

.Profile example, main
[source, yaml]
----
include::https://raw.githubusercontent.com/svt/encore-doc/main/src/docs/asciidoc/examples/profile/profiles.yml[]
----

.Profile example, x264 codec with forced keyframes
[source, yaml]
----
include::https://raw.githubusercontent.com/svt/encore-doc/main/src/docs/asciidoc/examples/profile/withforcekeyframe.yml[]
----

.Profile example, x264 codec
[source, yaml]
----
include::https://raw.githubusercontent.com/svt/encore-doc/main/src/docs/asciidoc/examples/profile/video.yml[]
----

=== The Future

We have a few ideas where we would like to go with Encore.
We are focusing on the features we need, but we are always open to suggestion and discussion, if you would like to contribute to the project.
