== Appendix

=== Application Properties

Beside the rich configuration possibilities of https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html[Spring Boot and friends], a few custom properties can be specified inside your application.properties file, inside your application.yml file, or as command line switches.

[[customapplicationproperties]]
.Custom Application Properties - *prefix: encore-settings*
[grid=none,frame=sides]
|===
| Key | Default | Description

| local-temporary-encode
| false
| if true, encoding is done in a temporary folder on the Encore instance currently running the job. When done, the results are moved to the where the Encore Job's output folder path is pointing.

| audio-mix-presets
|
| TODO

| concurrency
| 2
| Max nr of currently running encoding tasks (property starts at 0, so 0 gives 1 task).

| poll-initial-delay
| 10
| initial wait time in seconds before task starts.

| poll-delay
| 5
| wait before polling, in seconds, for next task after compilation of the current task.

| redis-key-prefix
| encore
| the prefix to identify your redis queue. Redis keys are named "$redisKeyPrefix-queue-$queueNo"

| security.enabled
| false
| enables basic auth, TODO: describe basic security logic

| security.user-password
|
| password for regular user

| security.admin-password
|
| password for the admin user

| open-api.title
| SVT Encore OpenAPI
| title shown in the OpenAPI url summary header

| open-api.description
| "Endpoints for Encore"
| description shown in the OpenAPI url summary header

| open-api.contact-name
|
| contact name shown in the OpenAPI gui summary header

| open-api.contact-email
|
| contact email shown in the OpenAPI gui summary header

| open-api.contact-url
|
| contact url shown in the OpenAPI gui summary header
|===

=== Homebrew AVTools

So you noticed that the FFmpeg Docker Example in the quickstart used the Repository Manager Brew?
The creators of *Encore*, have released their Brew Formulas on https://github.com/svt/homebrew-avtools[GitHub: Homebrew AVTools].

For example, here is the *Encore* FFmpeg Brew Formula that with minor modifications, uses formulas for X264, X265, and SVT's subtitle filter.

NOTE: To use and install this version of FFmpeg locally, follow the examples given at the https://github.com/svt/homebrew-avtools/blob/main/README.md[Homebrew AVTools README].

.The SVT *Encore* FFmpeg Brew Formula
[source, ruby]
----
include::https://raw.githubusercontent.com/svt/homebrew-avtools/main/Formula/ffmpeg-encore.rb[]
----

CAUTION: If you use Homebrew-AVTools, the version of FFmpeg in use might be updated without *any* notice.

=== Profiles

.Profile example, main
[source, yaml]
----
include::https://raw.githubusercontent.com/svt/encore-doc/main/src/docs/asciidoc/examples/profile/profiles.yml[]
----

.Profile example, x264 codec with forced keyframes
[source, yaml]
----
include::https://raw.githubusercontent.com/svt/encore-doc/main/src/docs/asciidoc/examples/profile/withforcekeyframe.yml[]
----

.Profile example, x264 codec
[source, yaml]
----
include::https://raw.githubusercontent.com/svt/encore-doc/main/src/docs/asciidoc/examples/profile/video.yml[]
----

=== The Future

We have a few ideas where we would like to go with Encore.
We are focusing on the features we need, but we are always open to suggestion and discussion, if you would like to contribute to the project.