== The Community Guide

General community information like the F.A.Q and links to Encore mentions.

[[faq]]
=== Frequently Asked Questions

==== How can I package my transcoded media for online streaming (DASH and HLS)?

You could have a look at https://google.github.io/shaka-packager/html/[Shaka Packager], https://github.com/axiomatic-systems/Bento4[Bento4], and configure them to process the output of *Encore*.

==== How can I generate my own OpenAPI documentation, for import into X

To create your own OpenAPI-export from *Encore* so that you can transform it as you wish:

[source,bash]
----
$ SPRING_PROFILES_ACTIVE=local ./gradlew clean generateOpenApiDocs
----

which will give you a _build/openapi.json_ file for further processing.

TIP: For further information on how you can configure the API-generation, see the https://springdoc.org/[Springdoc Project]

==== I have great idea/bugfix/improvement to Encore, how do I submit it?

See <<contributorguide, The Contribute section>>

==== Can I write a plugin/extension for doing X in *Encore*?

Currently, there are no extensions interface endpoints, but you could, for example, add transcoding functionality by writing an FFMpeg filter - some examples of how that can done can be found at https://github.com/SVT/ffmpeg-filter-proxy-filters[FFmpeg proxy filters] - have a peek at the https://github.com/svt/homebrew-avtools[Homebrew AVTools] for how to build an FFmpeg with them.

Also, open a discussion issue if you have any ideas regarding contributions about extensions to *Encore* that you want to discuss.

=== Articles and talks

https://conf.tube/videos/watch/751d41f4-72fd-4bfe-aa26-8d8b0e8054c2[Video: 2019 - FOSS made us do it]
- How *Encore* and FOSS tools enables the Video Encoding at SVT

https://medium.com/the-svt-tech-blog/encore-video-transcoding-at-its-core-b80c3e5658b3[Article: 2018 Encore - video transcoding at it's core]
- while interesting for the project origins, it contains partially *non-valid information* as the code has been largely rewritten since then.

=== Support

There is *no formal* support - none, nada, nothing - for *Encore* directly from the main contributors / maintainers - but we *would love if* people use and improve the project, so here are some suggestions if you are stuck.

*File an Issue on GitHub*

You can always file an issue, ask a question, open a discussion issue, and we will most likely respond to that when time allows.

*Stack Overflow*

If your question does not contain sensitive information, please ask a question on https://stackoverflow.com/[Stack Overflow] and use the tag 'encore'. Maybe some other users will help you.

[[projecthistory]]
=== Project History

*_The initiative_*

It was around 2018, and it was time to yet again update the license and the hardware for our proprietary non-flexible transcoding solution.
Although that unnamed solution had served us very well, we also had a history of less than optimal transcoding, flexibility and support when things went wrong.
Around that period, it happened that, our organisation was preparing the next "Tekniksprint".
A "Tekniksprint" is an "innovate for an entire sprint" period, which happens two times a year at our organisation.
That time, a small team gathered, with the purpose of seeing how much of a video transcoding solution that could be built in two weeks.
So, with warts, hacks and shortcuts, we had a fun Sprint period, and also ended up with something <<articles-and-talks, almost usable, see links>>.
And, yes, it even had GUI, so that we could make it pretty demo friendly.
However, it was not very robust, and something we could build further upon.

By having a Proof-of-Concept project, we now could now walk the long and winding internal organisation road of convincing everyone that we could, and that we should re-write the project seriously - considering flexibility, features and support in comparison with others.

*_The development_*

It almost became a meme for us, but in 2019 we wrote ut, tested it, and ran it in production, with so good results, that we could ditch out proprietary solution.
In fact, *Encore* helped us achieve better quality, better flexibility, and saved us money - the costs for developing the Encore solution was multitudes less than buying just another new stack.

We now had an easier way to work with new codecs and transcoding features that would be impossible, had we chosen another proprietary solution.

*_The Open Source Encore_*

We always had the intention to Open Source the solution, as we heard that others, mainly friends in Public Broadcast organisations, had an interest in the product.
So during 2019/20 , with almost every Sprint-period, we tried to have at least a task that was directly prepared with Open Sourcing Encore.
Slowly, but determined.

From license research, documentation, basic code cleanups, removing the most SVT-specific code, and releasing libraries that would make it possible to release the project itself.
Warts and all, finally we got there.

So far, Encore has been a success story for us at SVT.
We sincerely hope that it can benefit you, and with time grow to be an even greater transcoding solution.

/_The Videocore Team at SVT_

