=== Concepts

TODO:  PICTURE OF ENCORE OVERVIEW (FROM O's presentation)

=== Workflow

The workflow for an Encore Job can be described as:

1. An Encore Job is created
2. It is offered to a Queuefootnote:[In reality the Encore Job itself is not offered to, or polled from the queue - it is an Object QueueItem, which holds the needed metadata for the Encore Job]
3. At some point, the Encore Job is picked up from the Queue
4. Metadata needed for the coming transcoding task is gathered - for example, the input stream is analyzed, the Profile is read.
5. The transcoding is started - (FFmpeg transcoding starts)
6. Output files are written to the configured destination

.The Encore Job status field, roughly telling the observer the current position in the workflow (click to expand)
[%collapsible]
====
[source,kotlin]
----
include::https://raw.githubusercontent.com/svt/encore/master/src/main/kotlin/se/svt/oss/encore/model/Status.kt[]
----
====

==== Encore Job

_An *Encore* Job is the aggregate for the information needed to transcode a video - like streams, *profiles* and priorities._

* An *Encore* Job describes how a video file should be processed.
* An *Encore* Job can have several output streams, and one input stream.
* An *Encore* Job has a *_profile_*, which essentially describes how the job should configure it's transcoding.
* An *Encore* Job has a priority, which essentially describes how the job should be prioritized compared to other concurrent transcoding jobs.

==== Profile

_A *Profile* can be seen as a general abstraction of an FFmpeg configuration - example, bitrate to use, thumbnail generation, the codec to use._

* A *Profile* specifies the configuration for an *Encore* Job - general metadata, FFmpeg configuration and specific codec configuration.
* A *Profile* is specified in the yaml-format.
* A *Profile* should a clear, describing name - for example, YouTube-X264.yml.

See the <<profiles>> in the Appendix for examples.

==== Scaling, distribution and queues

_By using Redis as a (message broker) Queue system through the framework Redisson and an internal concurrency scheduler, a great of number of *Encore* instances can be set up._

* An *Encore* instance uses Redis through Redisson's _Priority Blocking Queue_. Jobs are scheduled on an *Encore* instance according to a given priority.
* Furthermore, on an instance, The *Encore* concurrency setting affects how many transcoding jobs be run on the same instance at once.

_So, From an *Encore* instance's point of view, the next EncoreJob is chosen for transcoding according to its priority (from Redis/Redisson Priority Queue) and according to how many concurrent tasks is allowed on the instance._


[#apiendpoints]
=== API/Endpoints

*Encore* is built using the framework Spring Rest Data, so most of the current REST API is based on the https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.fundamentals[default endpoints] generated from the usage of this framework. However, there also exists other Endpoints.

*Encore's* endpoints are described and self-documented in the https://www.openapis.org/[OpenAPIv3 format].


==== Live

To see and interact with the endpoints live, consult your

https://YOUR_RUNNING_ENCORE_INSTANCE/swagger-ui.html

TIP: This is the recommended way - dynamic, powerful and up-to-date.

==== Static

To see a static version of the API/Endpoint documentation, head to xref:openapi.adoc[Static Endpoints]


CAUTION: The statically generated documentation needs to be improved, and cleaned up, as it is autogenerated, with quite a few quirks. This would be ideally happen when the project is more mature.

===== Configure and Generate OpenAPI documentation

To create your own OpenAPI-export from *Encore* so that you transform it as you wish:

[source,bash]
----
$ SPRING_PROFILES_ACTIVE=local ./gradlew clean generateOpenApiDocs
----

which will give you a _build/openapi.json_ file for further processing.

TIP: For further information on how you can configure the API-generation, check out the https://springdoc.org/[Springdoc Project]

==== Developer

===== Encore Job

The Encore Job is the most central object in Encore. This is the object you POST and GET in the API.

The EncoreJob fields are documented in the <<live>> API, but also in the

xref:openapi.adoc#_encorejob[EncoreJob static documentation]

.The Encore Job class in Kotlin, for further clearification (click to expand)
[%collapsible]
====
[source,kotlin]
----
include::https://raw.githubusercontent.com/svt/encore/master/src/main/kotlin/se/svt/oss/encore/model/EncoreJob.kt[]
----
====

===== Profile

A profile consists of toplevel metadata, and a list of transcoding jobs.
The encodes list holds various types of Encoding types.
The Encoding types can be audio, video, thumbnail maps and so on.

See the <<profiles>> section in the Appendix for concrete, real life <<profile>> examples.

====== Profile Description

.toplevel: metadata for the profile
|===
|Field |Description |Constraint |Default

| name
| The name of the profile
|
|

| description
| A helpful description for the profile
|
|

| scaling
| Directly matching the FFmpeg scaling algorithm options
| If given, has to match one of the https://ffmpeg.org/ffmpeg-scaler.html[FFmpeg scaling algorithms]
| lanczos


| encodes
| a list of different encoding types for a profile
|  AudioEncode
   X264Encode
   X265Encode
   ThumbnailEncode
   ThumbnailMapEncode
|
|===

.type: VideoEncode (the base object for various videoencodes - X264Encode, X265Encode:
|===
|Field |Description |Constraint |Default

| width
| adds the https://ffmpeg.org/ffmpeg-filters.html#scale[scale filter], if scaling enabled
|
|  null, or -2 if only height is given

| height
| adds the https://ffmpeg.org/ffmpeg-filters.html#scale[scale filter], if scaling enabled
|
|  null, or -2 if only height is given

| twoPass
| true, false
| If FFmpeg transcoding should be https://en.wikipedia.org/wiki/Variable_bitrate#Multi-pass_encoding_and_single-pass_encoding[twoPass]
| true


| params
| general FFmpeg Encoding parameters (see <<profiles,examples>>, can be vsync etc)
|
|

| filters
| For adding extra https://ffmpeg.org/ffmpeg-filters.html[FFmpeg Filters]
|
|

| audioEncode
|
|
|

| format
| The file output format
|
| mp4

| suffix
| the suffix added to the output filename
|
|

| codec
| The codec library to use, set in the corresponding type
|
| Examples: libx264,libx265, libfdk_aac

| x264-params, x265-params
| Specific coding parameters for a specific codec library and type, see <<profiles>> for examples
|
| Examples: deblock, keyint
|===

.type: ThumbnailMapEncode - generate a thumbnailmap
|===
|Field |Description |Constraint |Default

| aspectWidth
|
|
| 16

| aspectHeight
|
|
| 9

| tileHeight
|
|
| 90

| cols
|
|
| 12

| rows
|
|
| 20
|===

.type: ThumbnailEncode - generate a thumbnail
|===
|Field |Description |Constraint |Default

| percentages
|
|
| [25, 50, 75]

| thumbnailWidth
|
|
| -2

| thumbnailHeight
|
|
| 1080
|===


.type: AudioEncode
|===
| Field | Description | Constraint | Default

| codec:
| The Audio library to use
|
|  libfdk_aac

| samplerate
| The audio samplerate
|
| 48000

| channels
| Number of channels for the audio
|
| 2

| suffix
|
|
| codec_nrofchannels.ch
|===



