== The User Guide

This part of the documentation describes how to get going with a quick start and installation hints.

=== Installation

Currently, there are no *pre-ready-to-go* installation packages, pods, docker images offered for *Encore*, but fear not - there are a few possibilities in how to get going. Continue reading!

==== Quickstart

[#requirements-run-local-boot]
* Encore requires:
** JDK 11 or later
** An available Redis instance (default configuration: locally installed port 6379)
** FFmpeg (we recommend the version present in https://github.com/svt/homebrew-avtools[Homebrew-AVTools] repository, which is what we use in our production environment)

===== Build the project

Run all tests and static analysis using:

[source,bash]
....
$ ./gradlew clean check
....

===== Option - Quick Test Trial: Run a local version with Spring Boot bootRun

You can run *Encore* on your local developer machine for a quick test trial by starting up a local developer Application Profile:

.In the *Encore* root folder:
[source,bash]
----
foobar@foo:~$ SPRING_PROFILES_ACTIVE=local ./gradlew clean bootRun
----

NOTE: This will use the _src/main/resources/application-local.yml_ configuration profile in *Encore*.

If the startup fails, verify that you are fulfilling the <<requirements-run-local-boot,requirements>>

Otherwise, verify that you can see the OpenAPI3 Swagger Gui in your browser, see <<dynamicapiendpoints>>.

Success?? Great - you might want to check out the <<concepts>> next.

===== Option - Docker Image: Run Encore in a Docker Image

This quickstart option will show you how to use https://docs.brew.sh/Homebrew-on-Linux[Homebrew] and create an FFmpeg Docker Image to run Encore from.

First, you need to create a base FFmpeg Docker image.
The following skeleton example installs a recent version of FFmpeg, with a few FFmpeg filters, and mediainfo.
Modify as needed.

.An FFmpeg Dockerfile example (click to expand)
[%collapsible]
====
[source,dockerfile]
----
include::examples/docker/FFmpegDockerfile[]
----

====

.With env variable DOCKER_BASE_IMAGE pointing to your FFmpeg Docker Image
[source,bash]
----
foobar@foo:~$ docker build -t encore-docker --build-arg DOCKER_BASE_IMAGE=<yourdockerbaseimage:youjustbuiltfromexample> . 

foobar@foo:~$ docker run --network=host -e SPRING_PROFILES_ACTIVE='local' encore-docker
----

Verify that you can see the OpenAPI3 Swagger Gui in your browser, see <<dynamicapiendpoints>>.

Success?? Great - you might want to check out the <<concepts>> next.


