== The User Guide

This part of the documentation describes how to build the project, a gives a few examples of how you can try-it-out locally.

=== Building the project

_Note: This step is not needed if you are trying out Encore with the_ <<example-using-docker-compose,Docker Compose example>>.

[#requirements-run-local-boot]
* Requires:
** JDK 11 or later
** An available Redis instance (default configuration: locally installed port 6379)
** FFmpeg and Mediainfo (we recommend the versions present in https://github.com/svt/homebrew-avtools[Homebrew-AVTools] repository, which has been tested to work with Encore).


To build **Encore**, with all tests, do:

[source,bash]
....
$ ./gradlew clean build
....

[source,bash]
....
$ ./gradlew clean build -x test
....

=== Try-it-out examples

A few examples on how you can try out **Encore**.

* Using Docker-Compose
* Using Spring Boot BootRun 
* Building an Docker Image and run Encore in a Docker Container

==== Example: using Docker Compose

* This step requires:
** https://docs.docker.com/compose/install/Docker-compose[Docker Compose]


- Use a docker-compose.yml

[source,yaml]
....
include::examples/docker/docker-compose.yml[]
....

and then

[source,console]
....
$ ./docker-compose up
....

and you should see Encore starting up.

IMPORTANT: By default, there are two folders mapped to your host system by using the example docker-compose file. 
**/tmp/input and /tmp/output**, which we will refer to as the **inputdir** and the **outputdir**
_Change these (in the docker-compose file) to something that suits your environment. 
The default should be fine on mac/linux._

- To find the IP Docker-Compose creates (so that you can access Encore's api).


[source,console]
....
$ docker inspect <nameOfDirectoryYouAreRunningFrom>_encorenet
....

NOTE: By design Docker-compose creates a network called <nameOfDirectoryYouAreRunningFrom>_encorenet


Got the IP? - great! Continue to <<posting-your-first-encorejob>>

==== Example: run Encore with Spring Boot bootRun

You can run *Encore* on your local machine by starting up a local developer Application Profile:

.In the *Encore* root folder:
[source,bash]
----
foobar@foo:~$ SPRING_PROFILES_ACTIVE=local ./gradlew clean bootRun
----

NOTE: This will use the _src/main/resources/application-local.yml_ configuration profile in *Encore*.

If the startup fails, verify that you are fulfilling the <<requirements-run-local-boot,requirements>>

Continue to <<posting-your-first-encorejob>>

==== Example: run Encore in a Docker Image

- Create or find a base FFmpeg/Mediainfo Docker image.

The given example installs a recent version of FFmpeg, with a few FFmpeg filters, and mediainfo.
Modify as needed, using a tap of https://docs.brew.sh/Homebrew-on-Linux[Homebrew] as an installation base.

.A FFmpeg Dockerfile example (click to expand)
[%collapsible]
====
[source,dockerfile]
----
include::examples/docker/FFmpegDockerfile[]
----

====

.With the environment variable DOCKER_BASE_IMAGE pointing to your FFmpeg Docker Image
[source,bash]
----
foobar@foo:~$ docker build -t encore-docker --build-arg DOCKER_BASE_IMAGE=<yourdockerbaseimage:youjustbuilt> . 

foobar@foo:~$ docker run --network=host -v /tmp/input:/tmp/input -v /tmp/output:/tmp/output -e SPRING_PROFILES_ACTIVE='local' encore-docker
----

Continue to <<posting-your-first-encorejob>>

=== Posting your first EncoreJob

* This step requires:
** A running instance of Encore
** A inputdir - where you put source files
** A outputdir - where you want the encoded files to end up


1) Use one of the files from the test resources in the Encore project and copy this to your **inputdir**
(Verify that you have access permissions to the **inputdir** and **outputdir**.)

[source,console]
....
$ cp src/test/resources/input/test.mp4 /tmp/input
....

2) Fire up a browser and http://<ENCORE_IP>:8080/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/ - i.e directly to the Encore Swagger Interface for Posting an EncoreJob.

3) Finally, Under POST, hit the "Try it out" button and POST this example. 
(Replace the *outputFolder* and *uri* with your **outputdir** and **inputdir**/filename.)


[source,json]
....

  {
  	"profile": "program",
  	"outputFolder": "/tmp/output",
  	"baseName": "quicktest_",
  	"inputs": [{
  		"uri": "/tmp/input/test.mp4",
  		"useFirstAudioStreams": 2,
  		"type": "AudioVideo"
  	}]
  }
....

You can now see some output in your terminal, and after a while you should see a couple of encoded files in the **outputdir**. 
Congratulations, you did your first encoding with Encore!

Now, find out more about specific options, see <<dynamicapiendpoints>>, or see the <<concepts>>.
